---
title: "Assignment_3_2"
author: "Mona Klau"
date: "2023-01-27"
output: html_document
---

Q3.2.1 
remind_me function
```{r}
remind_me <- function(){
  poffertjes_items <- c("yeast", "whole milk", "flour", "salt", "eggs", "butter", "powdered sugar")
  poffertjes_bake_off <- data.frame(poffertjes_items)
  print(poffertjes_bake_off)
  fondue_items <- c("kaas", "nootmuskaat", "brood", "groenten", "witte wijn")
  fondue_night <- data.frame(fondue_items)
  print(fondue_night)
}
remind_me()
```

Q3.2.1 
cheat function
```{r}
cheat <- function(exercise){ #takes argument exercise
  if (exercise == "Q3") {
    library(ggplot2)
    library(titanic)
    titanic_train$Survived[titanic_train$Survived == 0] <- "dead" #assign dead to Survived = 0
    titanic_train$Survived[titanic_train$Survived == 1] <- "alive" #assign alive to Survived = 1
    Q3_plot <- ggplot(data = titanic_train,
                      mapping = aes(x = Sex,
                                    fill = factor(Survived,
                                                  levels = c("dead", "alive")))) +
      geom_bar(position = "stack") + #stack bars on top of each other
      labs(fill = "How did it go?") #add legend label "How did it go?"
    return(Q3_plot)
  } 
  if (exercise == "Q5") {
    library(ggplot2)
    plot(ToothGrowth$supp, ToothGrowth$len)
    Q5_plot <-
      ggplot(data = ToothGrowth, mapping = aes(x = supp, y = len)) +
      geom_boxplot() #make plot with ggplot function to be able to change it
    Q5_improved <-
      Q5_plot + ggtitle("Plot of length by supp condition") + #adding title
      xlab("Teeth supp") + ylab("Teeth length") + #adding x and y axis labels
      theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 12)) + #customize title
      theme(axis.ticks.x = element_blank()) #removing x-axis ticks
    return(Q5_improved)
  }
  if (exercise == "Q7") {
    Q7_data <- ChickWeight
    Q7_plot <- ggplot(data = Q7_data, aes(x = Time, y = weight)) +
      geom_smooth(method = lm) #plot a smooth plot with x = Time and y = weight
    return(Q7_plot)
  }
}
cheat("Q7") #test function 
```

Q3.3.2
make_art() function that allows users to produce random art with set.seed argument. 
```{r}
make_art <- function(seed) {
  set.seed(seed)
  x <- seq(from = -3*pi, to = 3*pi, length.out = 5000)
  y1 <- sin(x*runif(1,1,4)) + rnorm(5000, mean = 0, sd = runif(1,0.1,1))
  y2 <- cos(x*runif(1,1,4)) + rnorm(5000, mean = 0, sd = runif(1,0.1,1))
  data <- data.frame(x = x, y = y1, y2 = y2,
                      color = colorRampPalette(brewer.pal(8, "Dark2"))(5000))
  ggplot(data) +
    geom_path(aes(x, y, color = color, group = cut_number(x, runif(1,20,100)))) +
    geom_path(aes(x, y2, color = color, group = cut_number(x, runif(1,20,100)))) +
    scale_color_identity() +
    theme_void() +
    theme(legend.position = "none")
  }
make_art(2)
```

